apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superhero-app
spec:
  destination:
    namespace: superhero
    server: https://kubernetes.default.svc
  source:
    path: k8s
    repoURL: https://github.com/edayalcin/superhero-fight-devops.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true